# coding: utf-8

"""
    Allele Calling Service

    The Allele Calling  service provides an API for converting raw sequence data to GFE and HLA allele calls.

    OpenAPI spec version: 0.0.3
    Contact: mhalagan@nmdp.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class AlleleCall(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'typing': 'list[Typing]',
        'features': 'list[Feature]',
        'ihiw_ref': 'list[Typing]',
        'full_gene': 'Feature',
        'gfe': 'str',
        'act_version': 'str',
        'gfe_version': 'str',
        'gfedb_version': 'str'
    }

    attribute_map = {
        'typing': 'typing',
        'features': 'features',
        'ihiw_ref': 'ihiw_ref',
        'full_gene': 'full_gene',
        'gfe': 'gfe',
        'act_version': 'act_version',
        'gfe_version': 'gfe_version',
        'gfedb_version': 'gfedb_version'
    }

    def __init__(self, typing=None, features=None, ihiw_ref=None, full_gene=None, gfe=None, act_version=None, gfe_version=None, gfedb_version=None):
        """
        AlleleCall - a model defined in Swagger
        """

        self._typing = None
        self._features = None
        self._ihiw_ref = None
        self._full_gene = None
        self._gfe = None
        self._act_version = None
        self._gfe_version = None
        self._gfedb_version = None

        if typing is not None:
          self.typing = typing
        if features is not None:
          self.features = features
        if ihiw_ref is not None:
          self.ihiw_ref = ihiw_ref
        if full_gene is not None:
          self.full_gene = full_gene
        if gfe is not None:
          self.gfe = gfe
        if act_version is not None:
          self.act_version = act_version
        if gfe_version is not None:
          self.gfe_version = gfe_version
        if gfedb_version is not None:
          self.gfedb_version = gfedb_version

    @property
    def typing(self):
        """
        Gets the typing of this AlleleCall.

        :return: The typing of this AlleleCall.
        :rtype: list[Typing]
        """
        return self._typing

    @typing.setter
    def typing(self, typing):
        """
        Sets the typing of this AlleleCall.

        :param typing: The typing of this AlleleCall.
        :type: list[Typing]
        """

        self._typing = typing

    @property
    def features(self):
        """
        Gets the features of this AlleleCall.

        :return: The features of this AlleleCall.
        :rtype: list[Feature]
        """
        return self._features

    @features.setter
    def features(self, features):
        """
        Sets the features of this AlleleCall.

        :param features: The features of this AlleleCall.
        :type: list[Feature]
        """

        self._features = features

    @property
    def ihiw_ref(self):
        """
        Gets the ihiw_ref of this AlleleCall.

        :return: The ihiw_ref of this AlleleCall.
        :rtype: list[Typing]
        """
        return self._ihiw_ref

    @ihiw_ref.setter
    def ihiw_ref(self, ihiw_ref):
        """
        Sets the ihiw_ref of this AlleleCall.

        :param ihiw_ref: The ihiw_ref of this AlleleCall.
        :type: list[Typing]
        """

        self._ihiw_ref = ihiw_ref

    @property
    def full_gene(self):
        """
        Gets the full_gene of this AlleleCall.

        :return: The full_gene of this AlleleCall.
        :rtype: Feature
        """
        return self._full_gene

    @full_gene.setter
    def full_gene(self, full_gene):
        """
        Sets the full_gene of this AlleleCall.

        :param full_gene: The full_gene of this AlleleCall.
        :type: Feature
        """

        self._full_gene = full_gene

    @property
    def gfe(self):
        """
        Gets the gfe of this AlleleCall.

        :return: The gfe of this AlleleCall.
        :rtype: str
        """
        return self._gfe

    @gfe.setter
    def gfe(self, gfe):
        """
        Sets the gfe of this AlleleCall.

        :param gfe: The gfe of this AlleleCall.
        :type: str
        """

        self._gfe = gfe

    @property
    def act_version(self):
        """
        Gets the act_version of this AlleleCall.

        :return: The act_version of this AlleleCall.
        :rtype: str
        """
        return self._act_version

    @act_version.setter
    def act_version(self, act_version):
        """
        Sets the act_version of this AlleleCall.

        :param act_version: The act_version of this AlleleCall.
        :type: str
        """

        self._act_version = act_version

    @property
    def gfe_version(self):
        """
        Gets the gfe_version of this AlleleCall.

        :return: The gfe_version of this AlleleCall.
        :rtype: str
        """
        return self._gfe_version

    @gfe_version.setter
    def gfe_version(self, gfe_version):
        """
        Sets the gfe_version of this AlleleCall.

        :param gfe_version: The gfe_version of this AlleleCall.
        :type: str
        """

        self._gfe_version = gfe_version

    @property
    def gfedb_version(self):
        """
        Gets the gfedb_version of this AlleleCall.

        :return: The gfedb_version of this AlleleCall.
        :rtype: str
        """
        return self._gfedb_version

    @gfedb_version.setter
    def gfedb_version(self, gfedb_version):
        """
        Sets the gfedb_version of this AlleleCall.

        :param gfedb_version: The gfedb_version of this AlleleCall.
        :type: str
        """

        self._gfedb_version = gfedb_version

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, AlleleCall):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
