# coding: utf-8

"""
    Allele Calling Service

    The Allele Calling  service provides an API for converting raw sequence data to GFE and HLA allele calls.

    OpenAPI spec version: 0.0.3
    Contact: mhalagan@nmdp.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class ArsCall(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'allele': 'str',
        'group_type': 'str',
        'group': 'str',
        'share_allele': 'list[Typing]',
        'act_version': 'str',
        'gfedb_version': 'str'
    }

    attribute_map = {
        'allele': 'allele',
        'group_type': 'group_type',
        'group': 'group',
        'share_allele': 'share_allele',
        'act_version': 'act_version',
        'gfedb_version': 'gfedb_version'
    }

    def __init__(self, allele=None, group_type=None, group=None, share_allele=None, act_version=None, gfedb_version=None):
        """
        ArsCall - a model defined in Swagger
        """

        self._allele = None
        self._group_type = None
        self._group = None
        self._share_allele = None
        self._act_version = None
        self._gfedb_version = None

        if allele is not None:
          self.allele = allele
        if group_type is not None:
          self.group_type = group_type
        if group is not None:
          self.group = group
        if share_allele is not None:
          self.share_allele = share_allele
        if act_version is not None:
          self.act_version = act_version
        if gfedb_version is not None:
          self.gfedb_version = gfedb_version

    @property
    def allele(self):
        """
        Gets the allele of this ArsCall.

        :return: The allele of this ArsCall.
        :rtype: str
        """
        return self._allele

    @allele.setter
    def allele(self, allele):
        """
        Sets the allele of this ArsCall.

        :param allele: The allele of this ArsCall.
        :type: str
        """

        self._allele = allele

    @property
    def group_type(self):
        """
        Gets the group_type of this ArsCall.

        :return: The group_type of this ArsCall.
        :rtype: str
        """
        return self._group_type

    @group_type.setter
    def group_type(self, group_type):
        """
        Sets the group_type of this ArsCall.

        :param group_type: The group_type of this ArsCall.
        :type: str
        """

        self._group_type = group_type

    @property
    def group(self):
        """
        Gets the group of this ArsCall.

        :return: The group of this ArsCall.
        :rtype: str
        """
        return self._group

    @group.setter
    def group(self, group):
        """
        Sets the group of this ArsCall.

        :param group: The group of this ArsCall.
        :type: str
        """

        self._group = group

    @property
    def share_allele(self):
        """
        Gets the share_allele of this ArsCall.

        :return: The share_allele of this ArsCall.
        :rtype: list[Typing]
        """
        return self._share_allele

    @share_allele.setter
    def share_allele(self, share_allele):
        """
        Sets the share_allele of this ArsCall.

        :param share_allele: The share_allele of this ArsCall.
        :type: list[Typing]
        """

        self._share_allele = share_allele

    @property
    def act_version(self):
        """
        Gets the act_version of this ArsCall.

        :return: The act_version of this ArsCall.
        :rtype: str
        """
        return self._act_version

    @act_version.setter
    def act_version(self, act_version):
        """
        Sets the act_version of this ArsCall.

        :param act_version: The act_version of this ArsCall.
        :type: str
        """

        self._act_version = act_version

    @property
    def gfedb_version(self):
        """
        Gets the gfedb_version of this ArsCall.

        :return: The gfedb_version of this ArsCall.
        :rtype: str
        """
        return self._gfedb_version

    @gfedb_version.setter
    def gfedb_version(self, gfedb_version):
        """
        Sets the gfedb_version of this ArsCall.

        :param gfedb_version: The gfedb_version of this ArsCall.
        :type: str
        """

        self._gfedb_version = gfedb_version

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, ArsCall):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
