# coding: utf-8

"""
    Allele Calling Service

    The Allele Calling  service provides an API for converting raw sequence data to GFE and HLA allele calls.

    OpenAPI spec version: 0.0.4
    Contact: mhalagan@nmdp.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class Typing(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'hla': 'str',
        'related_gfe': 'list[GfeTyping]'
    }

    attribute_map = {
        'hla': 'hla',
        'related_gfe': 'related_gfe'
    }

    def __init__(self, hla=None, related_gfe=None):
        """
        Typing - a model defined in Swagger
        """

        self._hla = None
        self._related_gfe = None

        if hla is not None:
          self.hla = hla
        if related_gfe is not None:
          self.related_gfe = related_gfe

    @property
    def hla(self):
        """
        Gets the hla of this Typing.

        :return: The hla of this Typing.
        :rtype: str
        """
        return self._hla

    @hla.setter
    def hla(self, hla):
        """
        Sets the hla of this Typing.

        :param hla: The hla of this Typing.
        :type: str
        """

        self._hla = hla

    @property
    def related_gfe(self):
        """
        Gets the related_gfe of this Typing.

        :return: The related_gfe of this Typing.
        :rtype: list[GfeTyping]
        """
        return self._related_gfe

    @related_gfe.setter
    def related_gfe(self, related_gfe):
        """
        Sets the related_gfe of this Typing.

        :param related_gfe: The related_gfe of this Typing.
        :type: list[GfeTyping]
        """

        self._related_gfe = related_gfe

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, Typing):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
