# coding: utf-8

from __future__ import absolute_import
from swagger_server.models.inline_response200_shares import InlineResponse200Shares
from swagger_server.models.inline_response200_typing import InlineResponse200Typing
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class InlineResponse200(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, typing: List[InlineResponse200Typing]=None, features: List[InlineResponse200Shares]=None, gfe: str=None, act_version: str=None, gfe_version: str=None, gfedb_version: str=None):
        """
        InlineResponse200 - a model defined in Swagger

        :param typing: The typing of this InlineResponse200.
        :type typing: List[InlineResponse200Typing]
        :param features: The features of this InlineResponse200.
        :type features: List[InlineResponse200Shares]
        :param gfe: The gfe of this InlineResponse200.
        :type gfe: str
        :param act_version: The act_version of this InlineResponse200.
        :type act_version: str
        :param gfe_version: The gfe_version of this InlineResponse200.
        :type gfe_version: str
        :param gfedb_version: The gfedb_version of this InlineResponse200.
        :type gfedb_version: str
        """
        self.swagger_types = {
            'typing': List[InlineResponse200Typing],
            'features': List[InlineResponse200Shares],
            'gfe': str,
            'act_version': str,
            'gfe_version': str,
            'gfedb_version': str
        }

        self.attribute_map = {
            'typing': 'typing',
            'features': 'features',
            'gfe': 'gfe',
            'act_version': 'act_version',
            'gfe_version': 'gfe_version',
            'gfedb_version': 'gfedb_version'
        }

        self._typing = typing
        self._features = features
        self._gfe = gfe
        self._act_version = act_version
        self._gfe_version = gfe_version
        self._gfedb_version = gfedb_version

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse200':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200 of this InlineResponse200.
        :rtype: InlineResponse200
        """
        return deserialize_model(dikt, cls)

    @property
    def typing(self) -> List[InlineResponse200Typing]:
        """
        Gets the typing of this InlineResponse200.

        :return: The typing of this InlineResponse200.
        :rtype: List[InlineResponse200Typing]
        """
        return self._typing

    @typing.setter
    def typing(self, typing: List[InlineResponse200Typing]):
        """
        Sets the typing of this InlineResponse200.

        :param typing: The typing of this InlineResponse200.
        :type typing: List[InlineResponse200Typing]
        """

        self._typing = typing

    @property
    def features(self) -> List[InlineResponse200Shares]:
        """
        Gets the features of this InlineResponse200.

        :return: The features of this InlineResponse200.
        :rtype: List[InlineResponse200Shares]
        """
        return self._features

    @features.setter
    def features(self, features: List[InlineResponse200Shares]):
        """
        Sets the features of this InlineResponse200.

        :param features: The features of this InlineResponse200.
        :type features: List[InlineResponse200Shares]
        """

        self._features = features

    @property
    def gfe(self) -> str:
        """
        Gets the gfe of this InlineResponse200.

        :return: The gfe of this InlineResponse200.
        :rtype: str
        """
        return self._gfe

    @gfe.setter
    def gfe(self, gfe: str):
        """
        Sets the gfe of this InlineResponse200.

        :param gfe: The gfe of this InlineResponse200.
        :type gfe: str
        """

        self._gfe = gfe

    @property
    def act_version(self) -> str:
        """
        Gets the act_version of this InlineResponse200.

        :return: The act_version of this InlineResponse200.
        :rtype: str
        """
        return self._act_version

    @act_version.setter
    def act_version(self, act_version: str):
        """
        Sets the act_version of this InlineResponse200.

        :param act_version: The act_version of this InlineResponse200.
        :type act_version: str
        """

        self._act_version = act_version

    @property
    def gfe_version(self) -> str:
        """
        Gets the gfe_version of this InlineResponse200.

        :return: The gfe_version of this InlineResponse200.
        :rtype: str
        """
        return self._gfe_version

    @gfe_version.setter
    def gfe_version(self, gfe_version: str):
        """
        Sets the gfe_version of this InlineResponse200.

        :param gfe_version: The gfe_version of this InlineResponse200.
        :type gfe_version: str
        """

        self._gfe_version = gfe_version

    @property
    def gfedb_version(self) -> str:
        """
        Gets the gfedb_version of this InlineResponse200.

        :return: The gfedb_version of this InlineResponse200.
        :rtype: str
        """
        return self._gfedb_version

    @gfedb_version.setter
    def gfedb_version(self, gfedb_version: str):
        """
        Sets the gfedb_version of this InlineResponse200.

        :param gfedb_version: The gfedb_version of this InlineResponse200.
        :type gfedb_version: str
        """

        self._gfedb_version = gfedb_version

