# coding: utf-8

from __future__ import absolute_import
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class InlineResponse2002(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, alleles: List[str]=None, feature_searched: str=None, start: int=None, end: int=None, sequences: List[str]=None, act_version: str=None, gfe_version: str=None, gfedb_version: str=None):
        """
        InlineResponse2002 - a model defined in Swagger

        :param alleles: The alleles of this InlineResponse2002.
        :type alleles: List[str]
        :param feature_searched: The feature_searched of this InlineResponse2002.
        :type feature_searched: str
        :param start: The start of this InlineResponse2002.
        :type start: int
        :param end: The end of this InlineResponse2002.
        :type end: int
        :param sequences: The sequences of this InlineResponse2002.
        :type sequences: List[str]
        :param act_version: The act_version of this InlineResponse2002.
        :type act_version: str
        :param gfe_version: The gfe_version of this InlineResponse2002.
        :type gfe_version: str
        :param gfedb_version: The gfedb_version of this InlineResponse2002.
        :type gfedb_version: str
        """
        self.swagger_types = {
            'alleles': List[str],
            'feature_searched': str,
            'start': int,
            'end': int,
            'sequences': List[str],
            'act_version': str,
            'gfe_version': str,
            'gfedb_version': str
        }

        self.attribute_map = {
            'alleles': 'alleles',
            'feature_searched': 'feature_searched',
            'start': 'start',
            'end': 'end',
            'sequences': 'sequences',
            'act_version': 'act_version',
            'gfe_version': 'gfe_version',
            'gfedb_version': 'gfedb_version'
        }

        self._alleles = alleles
        self._feature_searched = feature_searched
        self._start = start
        self._end = end
        self._sequences = sequences
        self._act_version = act_version
        self._gfe_version = gfe_version
        self._gfedb_version = gfedb_version

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse2002':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_2 of this InlineResponse2002.
        :rtype: InlineResponse2002
        """
        return deserialize_model(dikt, cls)

    @property
    def alleles(self) -> List[str]:
        """
        Gets the alleles of this InlineResponse2002.

        :return: The alleles of this InlineResponse2002.
        :rtype: List[str]
        """
        return self._alleles

    @alleles.setter
    def alleles(self, alleles: List[str]):
        """
        Sets the alleles of this InlineResponse2002.

        :param alleles: The alleles of this InlineResponse2002.
        :type alleles: List[str]
        """

        self._alleles = alleles

    @property
    def feature_searched(self) -> str:
        """
        Gets the feature_searched of this InlineResponse2002.

        :return: The feature_searched of this InlineResponse2002.
        :rtype: str
        """
        return self._feature_searched

    @feature_searched.setter
    def feature_searched(self, feature_searched: str):
        """
        Sets the feature_searched of this InlineResponse2002.

        :param feature_searched: The feature_searched of this InlineResponse2002.
        :type feature_searched: str
        """

        self._feature_searched = feature_searched

    @property
    def start(self) -> int:
        """
        Gets the start of this InlineResponse2002.

        :return: The start of this InlineResponse2002.
        :rtype: int
        """
        return self._start

    @start.setter
    def start(self, start: int):
        """
        Sets the start of this InlineResponse2002.

        :param start: The start of this InlineResponse2002.
        :type start: int
        """

        self._start = start

    @property
    def end(self) -> int:
        """
        Gets the end of this InlineResponse2002.

        :return: The end of this InlineResponse2002.
        :rtype: int
        """
        return self._end

    @end.setter
    def end(self, end: int):
        """
        Sets the end of this InlineResponse2002.

        :param end: The end of this InlineResponse2002.
        :type end: int
        """

        self._end = end

    @property
    def sequences(self) -> List[str]:
        """
        Gets the sequences of this InlineResponse2002.

        :return: The sequences of this InlineResponse2002.
        :rtype: List[str]
        """
        return self._sequences

    @sequences.setter
    def sequences(self, sequences: List[str]):
        """
        Sets the sequences of this InlineResponse2002.

        :param sequences: The sequences of this InlineResponse2002.
        :type sequences: List[str]
        """

        self._sequences = sequences

    @property
    def act_version(self) -> str:
        """
        Gets the act_version of this InlineResponse2002.

        :return: The act_version of this InlineResponse2002.
        :rtype: str
        """
        return self._act_version

    @act_version.setter
    def act_version(self, act_version: str):
        """
        Sets the act_version of this InlineResponse2002.

        :param act_version: The act_version of this InlineResponse2002.
        :type act_version: str
        """

        self._act_version = act_version

    @property
    def gfe_version(self) -> str:
        """
        Gets the gfe_version of this InlineResponse2002.

        :return: The gfe_version of this InlineResponse2002.
        :rtype: str
        """
        return self._gfe_version

    @gfe_version.setter
    def gfe_version(self, gfe_version: str):
        """
        Sets the gfe_version of this InlineResponse2002.

        :param gfe_version: The gfe_version of this InlineResponse2002.
        :type gfe_version: str
        """

        self._gfe_version = gfe_version

    @property
    def gfedb_version(self) -> str:
        """
        Gets the gfedb_version of this InlineResponse2002.

        :return: The gfedb_version of this InlineResponse2002.
        :rtype: str
        """
        return self._gfedb_version

    @gfedb_version.setter
    def gfedb_version(self, gfedb_version: str):
        """
        Sets the gfedb_version of this InlineResponse2002.

        :param gfedb_version: The gfedb_version of this InlineResponse2002.
        :type gfedb_version: str
        """

        self._gfedb_version = gfedb_version

