# coding: utf-8

from __future__ import absolute_import
from swagger_server.models.inline_response200_typing import InlineResponse200Typing
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class InlineResponse2001(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, allele: str=None, group_type: str=None, group: str=None, share_ars: List[InlineResponse200Typing]=None, act_version: str=None, gfe_version: str=None, gfedb_version: str=None):
        """
        InlineResponse2001 - a model defined in Swagger

        :param allele: The allele of this InlineResponse2001.
        :type allele: str
        :param group_type: The group_type of this InlineResponse2001.
        :type group_type: str
        :param group: The group of this InlineResponse2001.
        :type group: str
        :param share_ars: The share_ars of this InlineResponse2001.
        :type share_ars: List[InlineResponse200Typing]
        :param act_version: The act_version of this InlineResponse2001.
        :type act_version: str
        :param gfe_version: The gfe_version of this InlineResponse2001.
        :type gfe_version: str
        :param gfedb_version: The gfedb_version of this InlineResponse2001.
        :type gfedb_version: str
        """
        self.swagger_types = {
            'allele': str,
            'group_type': str,
            'group': str,
            'share_ars': List[InlineResponse200Typing],
            'act_version': str,
            'gfe_version': str,
            'gfedb_version': str
        }

        self.attribute_map = {
            'allele': 'allele',
            'group_type': 'group_type',
            'group': 'group',
            'share_ars': 'share_ars',
            'act_version': 'act_version',
            'gfe_version': 'gfe_version',
            'gfedb_version': 'gfedb_version'
        }

        self._allele = allele
        self._group_type = group_type
        self._group = group
        self._share_ars = share_ars
        self._act_version = act_version
        self._gfe_version = gfe_version
        self._gfedb_version = gfedb_version

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse2001':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_1 of this InlineResponse2001.
        :rtype: InlineResponse2001
        """
        return deserialize_model(dikt, cls)

    @property
    def allele(self) -> str:
        """
        Gets the allele of this InlineResponse2001.

        :return: The allele of this InlineResponse2001.
        :rtype: str
        """
        return self._allele

    @allele.setter
    def allele(self, allele: str):
        """
        Sets the allele of this InlineResponse2001.

        :param allele: The allele of this InlineResponse2001.
        :type allele: str
        """

        self._allele = allele

    @property
    def group_type(self) -> str:
        """
        Gets the group_type of this InlineResponse2001.

        :return: The group_type of this InlineResponse2001.
        :rtype: str
        """
        return self._group_type

    @group_type.setter
    def group_type(self, group_type: str):
        """
        Sets the group_type of this InlineResponse2001.

        :param group_type: The group_type of this InlineResponse2001.
        :type group_type: str
        """

        self._group_type = group_type

    @property
    def group(self) -> str:
        """
        Gets the group of this InlineResponse2001.

        :return: The group of this InlineResponse2001.
        :rtype: str
        """
        return self._group

    @group.setter
    def group(self, group: str):
        """
        Sets the group of this InlineResponse2001.

        :param group: The group of this InlineResponse2001.
        :type group: str
        """

        self._group = group

    @property
    def share_ars(self) -> List[InlineResponse200Typing]:
        """
        Gets the share_ars of this InlineResponse2001.

        :return: The share_ars of this InlineResponse2001.
        :rtype: List[InlineResponse200Typing]
        """
        return self._share_ars

    @share_ars.setter
    def share_ars(self, share_ars: List[InlineResponse200Typing]):
        """
        Sets the share_ars of this InlineResponse2001.

        :param share_ars: The share_ars of this InlineResponse2001.
        :type share_ars: List[InlineResponse200Typing]
        """

        self._share_ars = share_ars

    @property
    def act_version(self) -> str:
        """
        Gets the act_version of this InlineResponse2001.

        :return: The act_version of this InlineResponse2001.
        :rtype: str
        """
        return self._act_version

    @act_version.setter
    def act_version(self, act_version: str):
        """
        Sets the act_version of this InlineResponse2001.

        :param act_version: The act_version of this InlineResponse2001.
        :type act_version: str
        """

        self._act_version = act_version

    @property
    def gfe_version(self) -> str:
        """
        Gets the gfe_version of this InlineResponse2001.

        :return: The gfe_version of this InlineResponse2001.
        :rtype: str
        """
        return self._gfe_version

    @gfe_version.setter
    def gfe_version(self, gfe_version: str):
        """
        Sets the gfe_version of this InlineResponse2001.

        :param gfe_version: The gfe_version of this InlineResponse2001.
        :type gfe_version: str
        """

        self._gfe_version = gfe_version

    @property
    def gfedb_version(self) -> str:
        """
        Gets the gfedb_version of this InlineResponse2001.

        :return: The gfedb_version of this InlineResponse2001.
        :rtype: str
        """
        return self._gfedb_version

    @gfedb_version.setter
    def gfedb_version(self, gfedb_version: str):
        """
        Sets the gfedb_version of this InlineResponse2001.

        :param gfedb_version: The gfedb_version of this InlineResponse2001.
        :type gfedb_version: str
        """

        self._gfedb_version = gfedb_version

