# coding: utf-8

from __future__ import absolute_import
from swagger_server.models.gfe_typing import GfeTyping
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class Typing(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, hla: str=None, related_gfe: List[GfeTyping]=None):
        """
        Typing - a model defined in Swagger

        :param hla: The hla of this Typing.
        :type hla: str
        :param related_gfe: The related_gfe of this Typing.
        :type related_gfe: List[GfeTyping]
        """
        self.swagger_types = {
            'hla': str,
            'related_gfe': List[GfeTyping]
        }

        self.attribute_map = {
            'hla': 'hla',
            'related_gfe': 'related_gfe'
        }

        self._hla = hla
        self._related_gfe = related_gfe

    @classmethod
    def from_dict(cls, dikt) -> 'Typing':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Typing of this Typing.
        :rtype: Typing
        """
        return deserialize_model(dikt, cls)

    @property
    def hla(self) -> str:
        """
        Gets the hla of this Typing.

        :return: The hla of this Typing.
        :rtype: str
        """
        return self._hla

    @hla.setter
    def hla(self, hla: str):
        """
        Sets the hla of this Typing.

        :param hla: The hla of this Typing.
        :type hla: str
        """

        self._hla = hla

    @property
    def related_gfe(self) -> List[GfeTyping]:
        """
        Gets the related_gfe of this Typing.

        :return: The related_gfe of this Typing.
        :rtype: List[GfeTyping]
        """
        return self._related_gfe

    @related_gfe.setter
    def related_gfe(self, related_gfe: List[GfeTyping]):
        """
        Sets the related_gfe of this Typing.

        :param related_gfe: The related_gfe of this Typing.
        :type related_gfe: List[GfeTyping]
        """

        self._related_gfe = related_gfe

