# coding: utf-8

"""
    Gene Feature Enumeration Service

    The Gene Feature Enumeration (GFE) Submission service provides an API for converting raw sequence data to GFE. It provides both a RESTful API and a simple user interface for converting raw sequence data to GFE results. Sequences can be submitted one at a time or as a fasta file. This service uses <a href=\"https://github.com/nmdp-bioinformatics/service-feature\">nmdp-bioinformatics/service-feature</a> for encoding the raw sequence data and <a href=\"https://github.com/nmdp-bioinformatics/HSA\">nmdp-bioinformatics/HSA</a> for aligning the raw sequence data. The code is open source, and available on <a href=\"https://github.com/nmdp-bioinformatics/service-gfe-submission\">GitHub</a>.<br><br>Go to <a href=\"http://service-gfe-submission.readthedocs.io\">service-gfe-submission.readthedocs.io</a> for more information

    OpenAPI spec version: 1.0.7
    Contact: mhalagan@nmdp.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class Error(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, message=None, accession=None, file=None, gfe=None, log=None, rank=None, sequence=None, term=None, type=None, version=None):
        """
        Error - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'message': 'str',
            'accession': 'str',
            'file': 'str',
            'gfe': 'str',
            'log': 'list[str]',
            'rank': 'int',
            'sequence': 'str',
            'term': 'str',
            'type': 'str',
            'version': 'str'
        }

        self.attribute_map = {
            'message': 'Message',
            'accession': 'accession',
            'file': 'file',
            'gfe': 'gfe',
            'log': 'log',
            'rank': 'rank',
            'sequence': 'sequence',
            'term': 'term',
            'type': 'type',
            'version': 'version'
        }

        self._message = message
        self._accession = accession
        self._file = file
        self._gfe = gfe
        self._log = log
        self._rank = rank
        self._sequence = sequence
        self._term = term
        self._type = type
        self._version = version

    @property
    def message(self):
        """
        Gets the message of this Error.

        :return: The message of this Error.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message):
        """
        Sets the message of this Error.

        :param message: The message of this Error.
        :type: str
        """
        if message is None:
            raise ValueError("Invalid value for `message`, must not be `None`")

        self._message = message

    @property
    def accession(self):
        """
        Gets the accession of this Error.

        :return: The accession of this Error.
        :rtype: str
        """
        return self._accession

    @accession.setter
    def accession(self, accession):
        """
        Sets the accession of this Error.

        :param accession: The accession of this Error.
        :type: str
        """

        self._accession = accession

    @property
    def file(self):
        """
        Gets the file of this Error.

        :return: The file of this Error.
        :rtype: str
        """
        return self._file

    @file.setter
    def file(self, file):
        """
        Sets the file of this Error.

        :param file: The file of this Error.
        :type: str
        """

        self._file = file

    @property
    def gfe(self):
        """
        Gets the gfe of this Error.

        :return: The gfe of this Error.
        :rtype: str
        """
        return self._gfe

    @gfe.setter
    def gfe(self, gfe):
        """
        Sets the gfe of this Error.

        :param gfe: The gfe of this Error.
        :type: str
        """

        self._gfe = gfe

    @property
    def log(self):
        """
        Gets the log of this Error.

        :return: The log of this Error.
        :rtype: list[str]
        """
        return self._log

    @log.setter
    def log(self, log):
        """
        Sets the log of this Error.

        :param log: The log of this Error.
        :type: list[str]
        """

        self._log = log

    @property
    def rank(self):
        """
        Gets the rank of this Error.

        :return: The rank of this Error.
        :rtype: int
        """
        return self._rank

    @rank.setter
    def rank(self, rank):
        """
        Sets the rank of this Error.

        :param rank: The rank of this Error.
        :type: int
        """

        self._rank = rank

    @property
    def sequence(self):
        """
        Gets the sequence of this Error.

        :return: The sequence of this Error.
        :rtype: str
        """
        return self._sequence

    @sequence.setter
    def sequence(self, sequence):
        """
        Sets the sequence of this Error.

        :param sequence: The sequence of this Error.
        :type: str
        """

        self._sequence = sequence

    @property
    def term(self):
        """
        Gets the term of this Error.

        :return: The term of this Error.
        :rtype: str
        """
        return self._term

    @term.setter
    def term(self, term):
        """
        Sets the term of this Error.

        :param term: The term of this Error.
        :type: str
        """

        self._term = term

    @property
    def type(self):
        """
        Gets the type of this Error.

        :return: The type of this Error.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """
        Sets the type of this Error.

        :param type: The type of this Error.
        :type: str
        """

        self._type = type

    @property
    def version(self):
        """
        Gets the version of this Error.

        :return: The version of this Error.
        :rtype: str
        """
        return self._version

    @version.setter
    def version(self, version):
        """
        Sets the version of this Error.

        :param version: The version of this Error.
        :type: str
        """
        if version is None:
            raise ValueError("Invalid value for `version`, must not be `None`")

        self._version = version

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
