# coding: utf-8

"""
    Gene Feature Enumeration Service

    The Gene Feature Enumeration (GFE) Submission service provides an API for converting raw sequence data to GFE. It provides both a RESTful API and a simple user interface for converting raw sequence data to GFE results. Sequences can be submitted one at a time or as a fasta file. This service uses <a href=\"https://github.com/nmdp-bioinformatics/service-feature\">nmdp-bioinformatics/service-feature</a> for encoding the raw sequence data and <a href=\"https://github.com/nmdp-bioinformatics/HSA\">nmdp-bioinformatics/HSA</a> for aligning the raw sequence data. The code is open source, and available on <a href=\"https://github.com/nmdp-bioinformatics/service-gfe-submission\">GitHub</a>.<br><br>Go to <a href=\"http://service-gfe-submission.readthedocs.io\">service-gfe-submission.readthedocs.io</a> for more information

    OpenAPI spec version: 1.0.7
    Contact: mhalagan@nmdp.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class TypingData(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, locus=None, typing=None):
        """
        TypingData - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'locus': 'str',
            'typing': 'list[Typing]'
        }

        self.attribute_map = {
            'locus': 'locus',
            'typing': 'typing'
        }

        self._locus = locus
        self._typing = typing

    @property
    def locus(self):
        """
        Gets the locus of this TypingData.

        :return: The locus of this TypingData.
        :rtype: str
        """
        return self._locus

    @locus.setter
    def locus(self, locus):
        """
        Sets the locus of this TypingData.

        :param locus: The locus of this TypingData.
        :type: str
        """
        if locus is None:
            raise ValueError("Invalid value for `locus`, must not be `None`")

        self._locus = locus

    @property
    def typing(self):
        """
        Gets the typing of this TypingData.

        :return: The typing of this TypingData.
        :rtype: list[Typing]
        """
        return self._typing

    @typing.setter
    def typing(self, typing):
        """
        Sets the typing of this TypingData.

        :param typing: The typing of this TypingData.
        :type: list[Typing]
        """
        if typing is None:
            raise ValueError("Invalid value for `typing`, must not be `None`")

        self._typing = typing

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
