# coding: utf-8

"""
    Allele Calling Service

    The Allele Calling  service provides an API for converting raw sequence data to GFE and HLA allele calls.

    OpenAPI spec version: 0.0.3
    Contact: mhalagan@nmdp.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.feature import Feature


class TestFeature(unittest.TestCase):
    """ Feature unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFeature(self):
        """
        Test Feature
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = swagger_client.models.feature.Feature()
        pass


if __name__ == '__main__':
    unittest.main()
