# coding: utf-8

"""
    Allele Calling Service

    The Allele Calling  service provides an API for converting raw sequence data to GFE and HLA allele calls.

    OpenAPI spec version: 0.0.3
    Contact: mhalagan@nmdp.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """ DefaultApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.default_api.DefaultApi()

    def tearDown(self):
        pass

    def test_act_get(self):
        """
        Test case for act_get

        
        """
        pass

    def test_actformat_get(self):
        """
        Test case for actformat_get

        
        """
        pass

    def test_ars_get(self):
        """
        Test case for ars_get

        
        """
        pass

    def test_feature_get(self):
        """
        Test case for feature_get

        
        """
        pass

    def test_gfe_get(self):
        """
        Test case for gfe_get

        
        """
        pass


if __name__ == '__main__':
    unittest.main()
